### ISSUE TITLE
Object 'anno' doesn't exist?

### ISSUE THREAD

**Issue by getengqing** [SinaHonari/RCN#3]
when I run the: python  create_raw_afw.py   --src_dir=*   --dest_dir=* , 
there has a KeyError: "Unable to open object (Object 'anno' doesn't exist)".
How do solve it?

**Comment by SinaHonari** [comment]
The module expects the path to a folder that contains 'anno.mat'
There is information on top of the file on how to get the dataset and pass the unzipped folder as the input.
Did you follow those steps?

**Comment by getengqing** [comment]
I followed those steps and unzipped the dataset folder, but the error has retained.
Traceback (most recent call last):
  File "RCN/preprocessing/create_raw_afw.py", line 191, in <module>
    f_base = f[u'anno']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (~/h5py/h5py/_objects.c:2689)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (~/h5py/h5py/_objects.c:2647)
  File "/usr/local/lib/python2.7/dist-packages/h5py-2.6.0-py2.7-linux-x86_64.egg/h5py/_hl/group.py", line 169, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (~/h5py/h5py/_objects.c:2689)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (~/h5py/h5py/_objects.c:2647)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (~/h5py/h5py/h5o.c:3578)
KeyError: "Unable to open object (Object 'anno' doesn't exist)"

**Comment by SinaHonari** [comment]
Did you find the solution to this one as well?

**Comment by getengqing** [comment]
Yeah! The env and file path need reset, the will is OK~~~
